# ! Michael Rosenbaum 1.0.0 2019 11 12

# Theme info
remote_theme: mfrosenbaum/just-the-docs

# Search
search_enabled: true
# Enable support for hyphenated search words:
search_tokenizer_separator: /[\s/]+/

# Link behavior 
# This allows to link to subpages
heading_anchors: true

# Google Analytics Tracking 
ga_tracking: UA-6770433-5

# Add auxilary links:
aux_links: 
  "Innovations for Poverty Action": 
    - "//www.poverty-action.org/"
  "Global Poverty Research Lab": 
    - "//www.kellogg.northwestern.edu/research/global-poverty-research-lab.aspx"

# Change URLs and metadata
title: "Guides"
description: IPA & GPRL guides for data management of RCTs
baseurl: "/guides" 
url: "https://povertyaction.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: pretty

# add plugins
plugins:
    - jekyll-redirect-from

# Add logo
# Need to fix proportions 
#logo: "/assets/Combined_logo.png"